# Site settings
title: Peter and Lari 2020
tagline: "Wedding website like no other"
url: "https://github.com/peterpoliwoda/laripeter2020" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, lambda, package.json]
